<a href="https://colab.research.google.com/github/saleekah1234/Student-performance-analysis-system/blob/main/RandomForestClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import warnings

warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving training.csv to training.csv


In [ ]:
df = pd.read_csv("training.csv")
df.head()

Unnamed: 0 school sex  age  ... guardian_cat  famsize_cat address_cat  sex_cat
0           0     GP   F   18  ...            1            0           1        0
1           1     GP   F   17  ...            0            0           1        0
2           2     GP   F   15  ...            1            1           1        0
3           3     GP   F   15  ...            1            0           1        0
4           4     GP   F   16  ...            0            0           1        0

[5 rows x 51 columns]

In [ ]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [ ]:
df.head()

school sex  age address  ...  guardian_cat famsize_cat  address_cat  sex_cat
0     GP   F   18       U  ...             1           0            1        0
1     GP   F   17       U  ...             0           0            1        0
2     GP   F   15       U  ...             1           1            1        0
3     GP   F   15       U  ...             1           0            1        0
4     GP   F   16       U  ...             0           0            1        0

[5 rows x 50 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 50 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   school          1044 non-null   object
 1   sex             1044 non-null   object
 2   age             1044 non-null   int64 
 3   address         1044 non-null   object
 4   famsize         1044 non-null   int64 
 5   Pstatus         1044 non-null   object
 6   Medu            1044 non-null   int64 
 7   Fedu            1044 non-null   int64 
 8   Mjob            1044 non-null   object
 9   Fjob            1044 non-null   object
 10  reason          1044 non-null   object
 11  guardian        1044 non-null   object
 12  traveltime      1044 non-null   int64 
 13  studytime       1044 non-null   int64 
 14  failures        1044 non-null   int64 
 15  schoolsup       1044 non-null   object
 16  famsup          1044 non-null   object
 17  paid            1044 non-null   object
 18  activiti

In [ ]:
df1=df.copy()
df1 = df1.drop(columns=["sex","age",	"Pstatus",	"guardian",	"traveltime",	"schoolsup",	"famsup",	"paid",	"activities",	"nursery",	"higher",	"internet",	"romantic",	"freetime",	"goout",	"Dalc",	"Walc",	"health",	"absences",	"subject"	,"Regularity","G3","FinalGrade_cat","Regularity_cat",	"school_cat",	"GradeG1_cat"	,"GradeG2_cat"	,"reason_cat"	,"Mjob_cat"	,"Fjob_cat"	,"guardian_cat"	,"famsize_cat"	,"address_cat", "sex_cat"],axis=1)
df1.head()

school address  famsize  Medu  Fedu  ...  G1  G2 FinalGrade  GradeG1       GradeG2
0     GP       U        0     4     4  ...   5   6       Poor  Failure          Poor
1     GP       U        0     1     1  ...   5   5       Poor  Failure       Failure
2     GP       U        1     1     1  ...   7   8       Poor     Poor          Poor
3     GP       U        0     4     2  ...  15  14       Good     Good  Satisfactory
4     GP       U        0     3     3  ...   6  10       Poor     Poor          Poor

[5 rows x 16 columns]

In [ ]:
col_names = ["school",	"address",	"famsize",	"Medu",	"Fedu",	"Mjob",	"Fjob",	"reason",	"studytime",	"failures",	"famrel",	"G1",	"G2",	"FinalGrade",	"GradeG1"	,"GradeG2"	]


for col in col_names:
    
    print(df1[col].value_counts())   

GP    772
MS    272
Name: school, dtype: int64
U    759
R    285
Name: address, dtype: int64
0    738
1    306
Name: famsize, dtype: int64
4    306
2    289
3    238
1    202
0      9
Name: Medu, dtype: int64
2    324
1    256
3    231
4    224
0      9
Name: Fedu, dtype: int64
other       399
services    239
at_home     194
teacher     130
health       82
Name: Mjob, dtype: int64
other       584
services    292
teacher      65
at_home      62
health       41
Name: Fjob, dtype: int64
course        430
home          258
reputation    248
other         108
Name: reason, dtype: int64
2    503
1    317
3    162
4     62
Name: studytime, dtype: int64
0    861
1    120
2     33
3     30
Name: failures, dtype: int64
4    512
5    286
3    169
2     47
1     30
Name: famrel, dtype: int64
10    146
11    130
12    117
13    105
14    101
9      96
8      83
7      70
15     59
16     44
6      33
17     24
18     15
5      12
19      4
4       3
3       1
0       1
Name: G1, dtype: int64
11    

In [ ]:
df1['FinalGrade'].value_counts()

Satisfactory    457
Poor            320
Good            169
Failure          63
Excellent        35
Name: FinalGrade, dtype: int64

In [ ]:
df1.isnull().sum()

school        0
address       0
famsize       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
studytime     0
failures      0
famrel        0
G1            0
G2            0
FinalGrade    0
GradeG1       0
GradeG2       0
dtype: int64

In [ ]:
X = df1.drop(['FinalGrade'], axis=1)

y = df1['FinalGrade']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [ ]:
X_train.shape, X_test.shape

((835, 15), (209, 15))

In [ ]:
X_train.dtypes

school       object
address      object
famsize       int64
Medu          int64
Fedu          int64
Mjob         object
Fjob         object
reason       object
studytime     int64
failures      int64
famrel        int64
G1            int64
G2            int64
GradeG1      object
GradeG2      object
dtype: object

In [ ]:
X_train

school address  famsize  Medu  Fedu  ... famrel  G1  G2  GradeG1       GradeG2
89      GP       U        1     4     4  ...      4   8   6     Poor          Poor
704     GP       U        0     4     2  ...      5  10  12     Poor  Satisfactory
692     GP       R        0     2     2  ...      5   9  10     Poor          Poor
30      GP       U        0     4     4  ...      5   9  11     Poor  Satisfactory
317     GP       U        0     4     3  ...      4   9  10     Poor          Poor
..     ...     ...      ...   ...   ...  ...    ...  ..  ..      ...           ...
454     GP       U        0     4     2  ...      4  16  15     Good          Good
966     MS       U        0     2     1  ...      4   8   9     Poor          Poor
944     MS       R        0     4     2  ...      4  17  18     Good     Excellent
347     GP       U        0     4     3  ...      5  10  10     Poor          Poor
563     GP       R        0     2     3  ...      4   7   8     Poor          Poor

[835 rows x 15 columns]

In [ ]:
X_train['Mjob'].unique()

array(['teacher', 'health', 'other', 'at_home', 'services'], dtype=object)

In [ ]:
X_test.head()

school address  famsize  Medu  Fedu  ... famrel  G1  G2  GradeG1  GradeG2
975     MS       R        0     1     1  ...      4   8   9     Poor     Poor
522     GP       U        0     0     1  ...      3   9  10     Poor     Poor
413     GP       U        0     3     2  ...      5   8   8     Poor     Poor
905     MS       R        0     2     2  ...      5  15  17     Good     Good
328     GP       U        0     4     4  ...      5  10   9     Poor     Poor

[5 rows x 15 columns]

In [ ]:
y_train


89             Poor
704    Satisfactory
692            Poor
30     Satisfactory
317            Poor
           ...     
454            Good
966            Poor
944       Excellent
347            Poor
563            Poor
Name: FinalGrade, Length: 835, dtype: object

In [ ]:
!pip install category_encoders
import category_encoders as ce

     |████████████████████████████████| 81kB 2.8MB/s 


In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      1044 non-null   object
 1   address     1044 non-null   object
 2   famsize     1044 non-null   int64 
 3   Medu        1044 non-null   int64 
 4   Fedu        1044 non-null   int64 
 5   Mjob        1044 non-null   object
 6   Fjob        1044 non-null   object
 7   reason      1044 non-null   object
 8   studytime   1044 non-null   int64 
 9   failures    1044 non-null   int64 
 10  famrel      1044 non-null   int64 
 11  G1          1044 non-null   int64 
 12  G2          1044 non-null   int64 
 13  FinalGrade  1044 non-null   object
 14  GradeG1     1044 non-null   object
 15  GradeG2     1044 non-null   object
dtypes: int64(8), object(8)
memory usage: 130.6+ KB


In [ ]:
encoder = ce.OrdinalEncoder(cols = ["school","address","Mjob","Fjob",	"reason",	"GradeG1"	,"GradeG2"])


X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)


In [ ]:
y_train

89             Poor
704    Satisfactory
692            Poor
30     Satisfactory
317            Poor
           ...     
454            Good
966            Poor
944       Excellent
347            Poor
563            Poor
Name: FinalGrade, Length: 835, dtype: object

In [ ]:
y_test

975            Poor
522    Satisfactory
413            Poor
905            Good
328            Poor
           ...     
140         Failure
812            Good
432    Satisfactory
922            Poor
139            Good
Name: FinalGrade, Length: 209, dtype: object

In [ ]:
X_train.head()

school  address  famsize  Medu  Fedu  ...  famrel  G1  G2  GradeG1  GradeG2
89        1        1        1     4     4  ...       4   8   6        1        1
704       1        1        0     4     2  ...       5  10  12        1        2
692       1        2        0     2     2  ...       5   9  10        1        1
30        1        1        0     4     4  ...       5   9  11        1        2
317       1        1        0     4     3  ...       4   9  10        1        1

[5 rows x 15 columns]

In [ ]:
X_test.head()

school  address  famsize  Medu  Fedu  ...  famrel  G1  G2  GradeG1  GradeG2
975       2        2        0     1     1  ...       4   8   9        1        1
522       1        1        0     0     1  ...       3   9  10        1        1
413       1        1        0     3     2  ...       5   8   8        1        1
905       2        2        0     2     2  ...       5  15  17        3        3
328       1        1        0     4     4  ...       5  10   9        1        1

[5 rows x 15 columns]

In [ ]:
y_train

89             Poor
704    Satisfactory
692            Poor
30     Satisfactory
317            Poor
           ...     
454            Good
966            Poor
944       Excellent
347            Poor
563            Poor
Name: FinalGrade, Length: 835, dtype: object

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
regressor = RandomForestClassifier(criterion='gini', max_depth=4, n_estimators = 100, random_state = 43)

regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=43, verbose=0,
                       warm_start=False)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
print(y_pred)

['Poor' 'Poor' 'Poor' 'Good' 'Poor' 'Poor' 'Satisfactory' 'Failure'
 'Satisfactory' 'Satisfactory' 'Poor' 'Failure' 'Satisfactory' 'Poor'
 'Satisfactory' 'Satisfactory' 'Good' 'Excellent' 'Failure' 'Good' 'Good'
 'Satisfactory' 'Satisfactory' 'Poor' 'Satisfactory' 'Poor' 'Poor'
 'Satisfactory' 'Satisfactory' 'Satisfactory' 'Poor' 'Satisfactory' 'Poor'
 'Poor' 'Satisfactory' 'Failure' 'Good' 'Good' 'Good' 'Good' 'Poor' 'Poor'
 'Poor' 'Satisfactory' 'Good' 'Good' 'Satisfactory' 'Satisfactory'
 'Satisfactory' 'Poor' 'Satisfactory' 'Satisfactory' 'Satisfactory' 'Poor'
 'Good' 'Poor' 'Satisfactory' 'Good' 'Poor' 'Satisfactory' 'Satisfactory'
 'Poor' 'Poor' 'Satisfactory' 'Poor' 'Satisfactory' 'Poor' 'Satisfactory'
 'Satisfactory' 'Good' 'Good' 'Poor' 'Satisfactory' 'Good' 'Satisfactory'
 'Satisfactory' 'Satisfactory' 'Satisfactory' 'Satisfactory'
 'Satisfactory' 'Poor' 'Good' 'Satisfactory' 'Good' 'Satisfactory'
 'Satisfactory' 'Poor' 'Poor' 'Satisfactory' 'Satisfactory' 'Satisfactory'
 'Sa

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
print("Model Confusion Matrix :\n\n\n", confusion_matrix(y_test,y_pred))

Model Confusion Matrix :


 [[ 3  0  4  0  0]
 [ 0  9  0  4  0]
 [ 0  0 28  0 10]
 [ 0  1  0 52  5]
 [ 0  0  2  8 83]]


In [ ]:
print("Model Classification Report :\n\n\n", classification_report(y_test,y_pred))

Model Classification Report :


               precision    recall  f1-score   support

   Excellent       1.00      0.43      0.60         7
     Failure       0.90      0.69      0.78        13
        Good       0.82      0.74      0.78        38
        Poor       0.81      0.90      0.85        58
Satisfactory       0.85      0.89      0.87        93

    accuracy                           0.84       209
   macro avg       0.88      0.73      0.78       209
weighted avg       0.84      0.84      0.83       209



In [ ]:
print("Model Accuracy : ", accuracy_score(y_test, y_pred))

Model Accuracy :  0.8373205741626795


In [ ]:
X_train.to_csv("X_train dataset")

In [ ]:
y_pred_train = regressor.predict(X_train)
y_pred_train

array(['Poor', 'Satisfactory', 'Poor', 'Satisfactory', 'Poor', 'Poor',
       'Satisfactory', 'Satisfactory', 'Poor', 'Poor', 'Poor', 'Good',
       'Poor', 'Poor', 'Good', 'Poor', 'Satisfactory', 'Satisfactory',
       'Good', 'Failure', 'Satisfactory', 'Satisfactory', 'Satisfactory',
       'Satisfactory', 'Poor', 'Poor', 'Satisfactory', 'Poor', 'Poor',
       'Poor', 'Poor', 'Satisfactory', 'Poor', 'Poor', 'Satisfactory',
       'Poor', 'Good', 'Satisfactory', 'Poor', 'Satisfactory', 'Good',
       'Poor', 'Poor', 'Satisfactory', 'Poor', 'Poor', 'Satisfactory',
       'Poor', 'Satisfactory', 'Satisfactory', 'Poor', 'Good', 'Poor',
       'Satisfactory', 'Poor', 'Good', 'Satisfactory', 'Satisfactory',
       'Poor', 'Poor', 'Satisfactory', 'Satisfactory', 'Satisfactory',
       'Satisfactory', 'Satisfactory', 'Good', 'Good', 'Satisfactory',
       'Poor', 'Poor', 'Poor', 'Satisfactory', 'Poor', 'Satisfactory',
       'Satisfactory', 'Excellent', 'Satisfactory', 'Satisfactory',
      

In [ ]:
print("Training Accuracy : ", accuracy_score(y_train, y_pred_train))

Training Accuracy :  0.8359281437125748


In [ ]:
print("Training-Set Accuracy : ", regressor.score(X_train, y_train))
print("Testing-Set Accuracy : ", regressor.score(X_test, y_test))

Training-Set Accuracy :  0.8359281437125748
Testing-Set Accuracy :  0.8373205741626795


In [ ]:
y.unique()

array(['Poor', 'Good', 'Satisfactory', 'Excellent', 'Failure'],
      dtype=object)

In [ ]:
regressor.predict

<bound method ForestClassifier.predict of RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=43, verbose=0,
                       warm_start=False)>

In [ ]:



b=["School",	"Address",	"Family size",	"Mother Education",	"Father Education",	"Mother Job",	"Father Job","Reason",	"Study Time",	"Failure", "Family Relation",	"G1",	"G2"	,"Grade'G1"	,"GradeG2"]
a=[]
for i in range(0,15):
  a.append(input("Enter  "+b[i]+" : "))

if a[0]=="GP" :
  a[0]=1
else :
  a[0]=2


if a[1]=="U" :
  a[1]=1
else :
  a[1]=2


if a[5]=="teacher" :
  a[5]=1
elif a[5]=="health" :
  a[5]=2
elif a[5]=="other" :
  a[5]=3
elif a[5]=="at_home" :
  a[5]=4
else :
  a[5]=5


if a[6]=="health" :
  a[6]=1
elif a[6]=="other" :
  a[6]=2
elif a[6]=="services" :
  a[6]=3
elif a[6]=="teacher" :
  a[6]=4
else :
  a[6]=5


if a[7]=="reputation" :
  a[7]=1
elif a[7]=="other" :
  a[7]=2
elif a[7]=="home" :
  a[7]=3
elif a[7]=="course" :
  a[7]=4
else :
  a[7]=5


if a[13]=="Poor" :
  a[13]=1
elif a[13]=="Satisfactory" :
  a[13]=2
elif a[13]=="Good" :
  a[13]=3
elif a[13]=="Excellent" :
  a[13]=4
else :
  a[13]=5


if a[14]=="Poor" :
  a[14]=1
elif a[14]=="Satisfactory" :
  a[14]=2
elif a[14]=="Good" :
  a[14]=3
elif a[14]=="Failure" :
  a[14]=4
else :
  a[14]=5


regressor.predict([a])


Enter  School : MS
Enter  Address : 
Enter  Family size : 
Enter  Mother Education : 
Enter  Father Education : 
Enter  Mother Job : 
Enter  Father Job : 
Enter  Reason : 
Enter  Study Time : 
Enter  Failure : 
Enter  Family Relation : 
Enter  G1 : 
Enter  G2 : 
Enter  Grade'G1 : 
Enter  GradeG2 : 


ValueError: ignored